import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Heading/Header";
import AosInit from "@/components/AosInit";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ProductProvider } from "@/context/ProductContext";
import Footer from "@/components/Foot/Footer";
import { BackToTop } from "@/components/common/BackToTop";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProductProvider>
          <AosInit />
          <Header />
          <Toaster position="top-center" richColors />
          {children}
          <Footer />
          <BackToTop />
        </ProductProvider>
      </body>
    </html>
  );
}
